# Generated by Django 3.1.3 on 2020-11-28 23:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', ckeditor.fields.RichTextField()),
                ('technology', models.TextField(verbose_name='Techs')),
                ('image', models.ImageField(blank=True, null=True, upload_to='core/images', verbose_name='Imagem')),
                ('link', models.URLField(verbose_name='GitHub')),
                ('website', models.URLField(verbose_name='website')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Updated at')),
            ],
        ),
    ]
