# Generated by Django 3.1.3 on 2020-11-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='python developer', verbose_name='Atalho'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='website',
            field=models.URLField(blank=True, verbose_name='website'),
        ),
    ]
